version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./../:/var/www/html
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:1.23.2-alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./../public:/var/www/html/public
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mysql:/var/lib/mysql'
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

volumes:
    mysql:
    redis:


